apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: charlie
  namespace: default
  labels:
    gwcp.guidewire.com/app-name: charlie
spec:
  interval: 10m0s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: charlie
  namespace: default
  labels:
    gwcp.guidewire.com/app-name: charlie
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: charlie
      version: {{ .Values.charlie.version | quote }}
  interval: 10m0s
#  dependsOn:
#    - name: alpha
#    - name: bravo
#  values: {{ toYaml .Values.charlie.values | nindent 4 }}
#  {{- end }}
