---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-components
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/tedd-E/cluster-components.git
