---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-component
  namespace: flux-system
spec:
  interval: 1m
  secretRef:
    name: personal-git-auth
  ref:
    branch: main
  url: https://github.com/tedd-E/cluster-component.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: chart-one
  namespace: flux-system
spec:
  dependsOn:  # chart one depends on chart two for configmap
    - name: chart-two
  interval: 1m
  chart:
    spec:
      chart: ./chart-one
      sourceRef:
        kind: GitRepository
        name: cluster-component
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: chart-two   # this should be installed first by flux.....
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart-two
      sourceRef:
        kind: GitRepository
        name: cluster-component
